GET http://localhost:4000/subscribers

###

GET http://localhost:4000/subscribers/5fc7c2f23a568a206084d6f1

###

POST http://localhost:4000/subscribers
    Content-Type: application/json

{
    "name": "Jhon",
    "subscribedToChannel": "Clever Programming"
}

###

DELETE http://localhost:4000/subscribers/5fc7bf84ca26ab2504c04ebb

###

PATCH http://localhost:4000/subscribers/5fc7c2f23a568a206084d6f1
    Content-Type: application/json

{
    "name": "Peter",
    "subscribedToChannel": "Web develop"
}